### ISSUE TITLE
Far-field?

### ISSUE THREAD

**Issue by 79seismo** [fgallovic/RIKsrf#1]
Hi, 
Does the code work in the far-field as well? Say up to an epicentral distance of ~2000 - 3000 km? 

Thanks!

**Comment by fgallovic** [comment]
The RIKsrf code provides slip rates along the fault, which can be combined
with any Green's functions for any distances. However, you will have to
provide your own Green's functions because Axitra (DWN) considers only a
flat 1d velocity structure.



Dne út 5. 11. 2019 3:09 uživatel 79seismo <notifications@github.com> napsal:

**Comment by 79seismo** [comment]
Sounds good, thanks!
