### ISSUE TITLE
Can I use this package simulate ambient noise?

### ISSUE THREAD

**Issue by xichaoqiang** [fgallovic/RIKsrf#2]
Dear Author,

Can I use your DWN code to simulate ambient noise field ?

How can I set the parameters?

![image](https://user-images.githubusercontent.com/30900789/70802918-c05d0e00-1ded-11ea-8615-cba5a487697c.png)

Best regards
Xi

**Comment by fgallovic** [comment]
Dear Xi,
the dwn code is not particularly developed for this purpose. You would have
to calculate a lot of Green's functions for a lot of sources and convolve
them with various random source time functions (outside Axitra). You would
have to consider sources below the surface because of the limitations that
the receivers must be above the sources. The computational time might be
quite long because the shallower are the sources and the higher is the
demanded frequency, the slower is the calculation. But you can give it a
try.
Best regards,
Frantisek



pá 13. 12. 2019 v 14:17 odesílatel xichaoqiang <notifications@github.com>
napsal:
